### ISSUE TITLE
Include validation balance calling AmountValidationTrait->validateAmount

### ISSUE THREAD

**Issue by Japoivvb** [AlexLi727/M07_UF1_POO_Bank#1]
https://github.com/AlexLi727/M07_UF1_POO_Bank/blob/16feb8a61f66850a7ddb64eb0ca126539b86543a/src/ComBank/Bank/BankAccount.php#L28

**Comment by AlexLi727** [comment]
isssue solved in https://github.com/AlexLi727/M07_UF1_cURL_Bank
