### ISSUE TITLE
First validate later assign the input variable to attribute

### ISSUE THREAD

**Issue by Japoivvb** [AlexLi727/M07_UF1_POO_Bank#2]
https://github.com/AlexLi727/M07_UF1_POO_Bank/blob/16feb8a61f66850a7ddb64eb0ca126539b86543a/src/ComBank/Transactions/BaseTransaction.php#L23

**Comment by AlexLi727** [comment]
issue solved in https://github.com/AlexLi727/M07_UF1_cURL_Bank
